version: "3.5"
services:
  matrix-studrss-bot:
    build: .
    image: ghcr.io/neferin12/matrix-studrss-bot:latest
    container_name: matrixstudrssbot
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=postgres
    restart: unless-stopped
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ojihuztrde234hgf4567890kjhgf
      - POSTGRES_USER=local_user
      - POSTGRES_DB=studrss

volumes:
  data: